# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(0, 350, 1091, 261))
        self.log.setToolTip("")
        self.log.setObjectName("log")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 1091, 331))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.input.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.input.setObjectName("input")
        self.input.header().setCascadingSectionResizes(True)
        self.input.header().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.input)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.platform = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.platform.setEditable(True)
        self.platform.setObjectName("platform")
        self.verticalLayout.addWidget(self.platform)
        self.us = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.us.setEditable(False)
        self.us.setObjectName("us")
        self.verticalLayout.addWidget(self.us)
        self.sign = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sign.setObjectName("sign")
        self.verticalLayout.addWidget(self.sign)
        self.child_dirs = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.child_dirs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.child_dirs.sizePolicy().hasHeightForWidth())
        self.child_dirs.setSizePolicy(sizePolicy)
        self.child_dirs.setMaximumSize(QtCore.QSize(90, 16777215))
        self.child_dirs.setObjectName("child_dirs")
        self.verticalLayout.addWidget(self.child_dirs)
        self.install = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.install.setObjectName("install")
        self.verticalLayout.addWidget(self.install)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.output = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.output.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.output.setObjectName("output")
        self.horizontalLayout.addWidget(self.output)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input.setToolTip(_translate("MainWindow", "选择一个准备签名的文件，中间调整好参数之后点击【签名】按钮即可开始"))
        self.sign.setToolTip(_translate("MainWindow", "根据左侧选择的文件进行签名，签名返回文件存放在右侧窗口，返回文件名会按照签名参数和时间的拼接"))
        self.sign.setText(_translate("MainWindow", "<<签名"))
        self.child_dirs.setToolTip(_translate("MainWindow", "签名文件在存放在当前目录的子目录下面，请填写子目录名如：apks/today/，或空为当前目录存储"))
        self.child_dirs.setPlaceholderText(_translate("MainWindow", "存放子目录"))
        self.install.setToolTip(_translate("MainWindow", "安装右侧文件"))
        self.install.setText(_translate("MainWindow", "安装>>"))
        self.output.setToolTip(_translate("MainWindow", "签名返回的文件存储路径，可指定存放在子目录下面，默认存储在当前目录"))
